SystemManager:
  libraries:
    - requests==2.31.0
    - pyyaml==6.0.2
  parameters:
    - system_config_path: "system_config.yaml"
  import_path: from rakam_systems.system_manager import SystemManager

DataProcessor:
  libraries:
    - pandas==2.1.4
    - tqdm==4.66.4
    - python-magic==0.4.27
    - pymupdf==1.24.11
    - pymupdf4llm==0.0.17
  parameters:
    - system_manager: system_manager
  import_path: from rakam_systems.components.data_processing.data_processor import DataProcessor

VSManager:
  libraries:
    - faiss-cpu==1.8.0.post1
    - sentence-transformers==3.2.1
    - joblib==1.4.2
  parameters:
    - system_manager: system_manager
    - base_index_path: "data/vector_stores_for_test/example_baseIDXpath"
    - embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  import_path: from rakam_systems.components.vector_search.vs_manager import VSManager

VectorStore:
  libraries:
    - faiss-cpu==1.8.0.post1
    - sentence-transformers==3.2.1
    - joblib==1.4.2
  parameters:
    - system_manager: system_manager
    - base_index_path: "data/vector_stores_for_test/example_baseIDXpath"
    - embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  import_path: from rakam_systems.components.vector_search.vector_store import VectorStore

LLMManager:
  libraries:
    - openai==1.37.0
    - mistralai==1.1.0
    - requests==2.31.0
  parameters:
    - system_manager: system_manager
    - model: "mistral-large-latest"
  import_path: from rakam_systems.components.connectors.LLMconnector import LLMManager

S3FileManager:
  libraries:
    - boto3==1.34.115
  parameters:
    - system_manager: system_manager
    - bucket_name: "rakam-test-rs"
  import_path: from rakam_systems.components.connectors.file_storage import S3FileManager

RAGGenerator:
  libraries:
    - openai==1.37.0
    - mistralai==1.1.0
    - requests==2.31.0
    - sentence-transformers==3.2.1
  parameters:
    - system_manager: system_manager
  import_path: from rakam_systems.components.rag.rag_generator import RAGGenerator

ServerGroups:
  - name: injection_server
    components:
      - DataProcessor
      - VSManager
      - S3FileManager
      - SystemManager

  - name: vector_search_server
    components:
      - VectorStore
      - S3FileManager
      - SystemManager

  - name: generation_server
    components:
      - LLMManager
      - RAGGenerator    
      - S3FileManager
      - SystemManager
